### ISSUE TITLE
Would you care to publish a package based on MarkDig.Signed too?

### ISSUE THREAD

**Issue by Atrejoe** [leisn/MarkdigToc#1]
Markdig publishes a signed version. (https://www.nuget.org/packages/Markdig.Signed/)
Would you care to release a signed version, based on this package too?

Thanks for sharing your work!

**Comment by leisn** [comment]
> This addresses #1
> 
> Would you care to review and publish it?
> 
> I did some minor changes to the tests too. One tests (`MdFilesTest`) fails (on the unaltered codetoo), but I haven't found out why. This may be some encoding thing.

I noticed that. The `MdFilesTest` failed because of the newline character.  `\r\n` not equal `\n`. Change the `*.html` files to `LF` from `CRLF` can fix it. 
And about the signed version, thanks for your code, I will consider merge your pull request.
